version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  mysql:
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    image: mysql
    volumes:
      - ./dev_data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
