# frozen_string_literal: true

class ChangeAutoGeneratedNamesToBeText < ActiveRecord::Migration[7.0]
  def up
    # extraction_definitions
    remove_index :extraction_definitions, %i[content_partner_id name], unique: true
    remove_index :extraction_definitions, %i[name]
    change_column :extraction_definitions, :name, :text

    # harvest_definitions
    remove_index :harvest_definitions, %i[content_partner_id name], unique: true
    change_column :harvest_definitions, :name, :text

    # harvest_jobs
    change_column :harvest_jobs, :name, :text

    # transformation_definitions
    remove_index :transformation_definitions, %i[content_partner_id name], unique: true
    remove_index :transformation_definitions, %i[name]
    change_column :transformation_definitions, :name, :text
  end

  def down
    # extraction_definitions
    change_column :extraction_definitions, :name, :string
    add_index :extraction_definitions, %i[name]
    add_index :extraction_definitions, %i[content_partner_id name], unique: true

    # harvest_definitions
    change_column :harvest_definitions, :name, :string
    add_index :harvest_definitions, %i[content_partner_id name], unique: true

    # harvest_jobs
    change_column :harvest_jobs, :name, :string

    # transformation_definitions
    change_column :transformation_definitions, :name, :string
    add_index :transformation_definitions, %i[name]
    add_index :transformation_definitions, %i[content_partner_id name], unique: true
  end
end
